### ISSUE TITLE
A error of demo 

### ISSUE THREAD

**Issue by TianyiHuang0224** [MattJBritton/ExquisiteCorrpse#1] opened 2020-08-15 13:15 UTC
ValueError                                Traceback (most recent call last)
<ipython-input-31-e7a0d7f5be38> in <module>
----> 1 visualize_feature_correlation(boston_df, "heatmap").properties(title="Boston Housing Data Correlation Matrix")

<ipython-input-30-262335e27672> in visualize_feature_correlation(data, chart_type, target_name, cluster_scope, user_defined_clusters)
      9     corr_condensed = hc.distance.squareform(1 - np.abs(df.corr()) ) # convert to condensed
     10     z = hc.linkage(corr_condensed, method='average');
---> 11     feature_order = hc.dendrogram(z, labels=df.columns, no_plot=True)["ivl"];
     12     if chart_type == "dendrogram":
     13         fig = ff.create_dendrogram(

D:\Program Files\anaconda3\lib\site-packages\scipy\cluster\hierarchy.py in dendrogram(Z, p, truncate_mode, color_threshold, get_leaves, orientation, labels, count_sort, distance_sort, show_leaf_counts, no_plot, no_labels, leaf_font_size, leaf_rotation, leaf_label_func, show_contracted, link_color_func, ax, above_threshold_color)
   3275                          "'bottom', or 'right'")
   3276 
-> 3277     if labels and Z.shape[0] + 1 != len(labels):
   3278         raise ValueError("Dimensions of Z and labels must be consistent.")
   3279 

D:\Program Files\anaconda3\lib\site-packages\pandas\core\indexes\base.py in __nonzero__(self)
   2147 
   2148     def __nonzero__(self):
-> 2149         raise ValueError(
   2150             f"The truth value of a {type(self).__name__} is ambiguous. "
   2151             "Use a.empty, a.bool(), a.item(), a.any() or a.all()."

ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by MattJBritton** [comment] 2020-08-16 04:01
Hello @TianyiHuang0224! First of all, thanks for taking the time investigate this project of mine. It is greatly appreciated!

It looks like this was caused by an error in SciPy (`scipy.cluster.hierarchy.dendrogram`). That [issue](https://github.com/scipy/scipy/pull/12421) was fixed in v1.5.2, so I'd just update your scipy in conda and you should be good to go.

I should put in a YML file for a conda environment - thanks for bringing that to my attention.

**Closed** 2020-08-16 04:02 UTC
